import { TransformOperation, EngineType } from '../types';

// ──────────────────────────────────────────────
// DuckDB Code Generation
// ──────────────────────────────────────────────

export function generateDuckDBSQL(steps: TransformOperation[], filePath?: string): string {
  if (steps.length === 0) {
    return '-- No transforms applied';
  }

  const lines: string[] = [
    '-- Generated by QuackWrangler',
    '-- Engine: DuckDB',
    '',
  ];

  if (filePath) {
    lines.push(`-- Source: ${filePath}`);
    lines.push('');
  }

  steps.forEach((step, index) => {
    lines.push(`-- Step ${index + 1}: ${step.description}`);
    lines.push(step.sql);
    lines.push('');
  });

  return lines.join('\n');
}

export function generateDuckDBPython(steps: TransformOperation[], filePath?: string): string {
  const lines: string[] = [
    '# Generated by QuackWrangler',
    '# Engine: DuckDB',
    '',
    'import duckdb',
    '',
    'con = duckdb.connect()',
    '',
  ];

  if (filePath) {
    lines.push(`# Source: ${filePath}`);
    lines.push(`df = con.read_parquet('${filePath}')`);
    lines.push('con.register("current_data", df)');
    lines.push('');
  }

  steps.forEach((step, index) => {
    lines.push(`# Step ${index + 1}: ${step.description}`);
    const escapedSql = step.sql.replace(/'/g, "\\'");
    lines.push(`con.execute('${escapedSql}')`);
    lines.push('');
  });

  lines.push('result = con.execute("SELECT * FROM current_data").fetchall()');
  lines.push('print(result)');

  return lines.join('\n');
}

// ──────────────────────────────────────────────
// Polars Code Generation
// ──────────────────────────────────────────────

export function generatePolarsPython(steps: TransformOperation[], filePath?: string): string {
  const lines: string[] = [
    '# Generated by QuackWrangler',
    '# Engine: Polars',
    '',
    'import polars as pl',
    '',
  ];

  if (filePath) {
    lines.push(`# Source: ${filePath}`);
    lines.push(`df = pl.read_parquet('${filePath}')`);
  } else {
    lines.push('df = pl.DataFrame()');
  }

  lines.push('');

  steps.forEach((step, index) => {
    lines.push(`# Step ${index + 1}: ${step.description}`);
    const polarsCode = transformToPolars(step);
    lines.push(polarsCode);
    lines.push('');
  });

  lines.push('print(df)');
  lines.push('print(f"Shape: {df.shape}")');

  return lines.join('\n');
}

function transformToPolars(step: TransformOperation): string {
  switch (step.type) {
    case 'dropColumn': {
      const cols = step.params.columns as string[];
      return `df = df.drop(${cols.map(c => `"${c}"`).join(', ')})`;
    }

    case 'renameColumn': {
      const renames = step.params.renames as Record<string, string>;
      const renameMap = Object.entries(renames)
        .map(([old, new_]) => `"${old}": "${new_}"`)
        .join(', ');
      return `df = df.rename({${renameMap}})`;
    }

    case 'filterRows': {
      const condition = step.params.condition as string;
      return `df = df.filter(pl.col("${condition}"))`;
    }

    case 'sortRows': {
      const { column, ascending } = step.params as { column: string; ascending: boolean };
      const nullsLast = ', nulls_last=True';
      return ascending
        ? `df = df.sort("${column}"${nullsLast})`
        : `df = df.sort("${column}", descending=True${nullsLast})`;
    }

    case 'castType': {
      const { column, targetType } = step.params as { column: string; targetType: string };
      return `df = df.with_columns(pl.col("${column}").cast(pl.${targetType}))`;
    }

    case 'fillMissing': {
      const { column, value } = step.params as { column: string; value: string };
      return `df = df.with_columns(pl.col("${column}").fill_null(${value}))`;
    }

    case 'deduplicate': {
      const cols = step.params.columns as string[];
      return `df = df.unique(subset=[${cols.map(c => `"${c}"`).join(', ')}])`;
    }

    case 'oneHotEncode': {
      const col = step.params.column as string;
      return [
        `categories = df["${col}"].unique().to_list()`,
        `for cat in categories:`,
        `    df = df.with_columns((pl.col("${col}") == cat).cast(pl.Int8).alias(f"${col}_{cat}"))`,
      ].join('\n    ');
    }

    case 'normalize': {
      const col = step.params.column as string;
      return `df = df.with_columns(((pl.col("${col}") - pl.col("${col}").min()) / (pl.col("${col}").max() - pl.col("${col}").min())).alias("${col}_normalized"))`;
    }

    case 'splitColumn': {
      const { column, delimiter } = step.params as { column: string; delimiter: string };
      return `df = df.with_columns(pl.col("${column}").str.split("${delimiter}").alias("${column}_parts"))`;
    }

    case 'mergeColumns': {
      const { columns, separator, newColumn } = step.params as { columns: string[]; separator: string; newColumn: string };
      const castExpr = columns.map(c => `pl.col("${c}").cast(pl.Utf8)`).join(`.str.concat(pl.lit("${separator}")).`);
      return `df = df.with_columns(${castExpr}.alias("${newColumn}"))`;
    }

    default:
      return `# Unsupported transform for Polars: ${step.type}`;
  }
}

// ──────────────────────────────────────────────
// Unified Code Generation (engine-aware)
// ──────────────────────────────────────────────

export function generateCode(
  steps: TransformOperation[],
  engine: EngineType,
  filePath?: string,
  format: 'sql' | 'python' = 'python',
): string {
  if (engine === 'duckdb') {
    return format === 'sql'
      ? generateDuckDBSQL(steps, filePath)
      : generateDuckDBPython(steps, filePath);
  } else {
    return generatePolarsPython(steps, filePath);
  }
}

export function wrapAsView(step: TransformOperation, viewName: string): string {
  const safeName = viewName.replace(/[^a-zA-Z0-9_]/g, '_');
  return `CREATE OR REPLACE VIEW ${safeName} AS ${step.sql}`;
}

export function exportToNotebook(
  steps: TransformOperation[],
  engine: EngineType = 'duckdb',
  filePath?: string,
): string {
  const cells: any[] = [];

  cells.push({
    cell_type: 'markdown',
    metadata: {},
    source: [
      '# QuackWrangler Notebook',
      '',
      `Engine: ${engine === 'duckdb' ? 'DuckDB' : 'Polars'}`,
      '',
      'Data wrangling steps exported from QuackWrangler.',
    ],
  });

  if (engine === 'duckdb') {
    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['import duckdb', '', 'con = duckdb.connect()'],
      outputs: [],
      execution_count: null,
    });

    if (filePath) {
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [`df = con.read_parquet('${filePath}')`, 'con.register("current_data", df)'],
        outputs: [],
        execution_count: null,
      });
    }

    steps.forEach((step, index) => {
      cells.push({
        cell_type: 'markdown',
        metadata: {},
        source: [`## Step ${index + 1}: ${step.description}`],
      });

      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [step.sql, '', 'con.execute(step_sql)'],
        outputs: [],
        execution_count: null,
      });
    });

    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['result = con.execute("SELECT * FROM current_data").fetchall()', 'print(result)'],
      outputs: [],
      execution_count: null,
    });
  } else {
    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['import polars as pl'],
      outputs: [],
      execution_count: null,
    });

    if (filePath) {
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [`df = pl.read_parquet('${filePath}')`],
        outputs: [],
        execution_count: null,
      });
    }

    steps.forEach((step, index) => {
      cells.push({
        cell_type: 'markdown',
        metadata: {},
        source: [`## Step ${index + 1}: ${step.description}`],
      });

      const polarsCode = transformToPolars(step);
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [polarsCode],
        outputs: [],
        execution_count: null,
      });
    });

    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['print(df)', 'print(f"Shape: {df.shape}")'],
      outputs: [],
      execution_count: null,
    });
  }

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.10.0',
      },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
