import { TransformOperation } from '../types';

export function generateDuckDBSQL(steps: TransformOperation[]): string {
  if (steps.length === 0) {
    return '-- No transforms applied';
  }

  const lines: string[] = [
    '-- Generated by QuackWrangler',
    '-- DuckDB SQL',
    '',
  ];

  steps.forEach((step, index) => {
    lines.push(`-- Step ${index + 1}: ${step.description}`);
    lines.push(step.sql);
    lines.push('');
  });

  return lines.join('\n');
}

export function generatePythonCode(steps: TransformOperation[]): string {
  const lines: string[] = [
    'import duckdb',
    '',
    'con = duckdb.connect()',
    '',
  ];

  steps.forEach((step, index) => {
    lines.push(`# Step ${index + 1}: ${step.description}`);
    const escapedSql = step.sql.replace(/'/g, "\\'");
    lines.push(`con.execute('${escapedSql}')`);
    lines.push('');
  });

  lines.push('result = con.execute("SELECT * FROM current_data").fetchall()');
  lines.push('print(result)');

  return lines.join('\n');
}

export function wrapAsView(step: TransformOperation, viewName: string): string {
  const safeName = viewName.replace(/[^a-zA-Z0-9_]/g, '_');
  return `CREATE OR REPLACE VIEW ${safeName} AS ${step.sql}`;
}

export function exportToNotebook(steps: TransformOperation[]): string {
  const cells: any[] = [];

  cells.push({
    cell_type: 'markdown',
    metadata: {},
    source: ['# QuackWrangler Notebook', '', 'Data wrangling steps exported from QuackWrangler.'],
  });

  cells.push({
    cell_type: 'code',
    metadata: {},
    source: ['import duckdb', '', 'con = duckdb.connect()'],
    outputs: [],
    execution_count: null,
  });

  steps.forEach((step, index) => {
    cells.push({
      cell_type: 'markdown',
      metadata: {},
      source: [`## Step ${index + 1}: ${step.description}`],
    });

    cells.push({
      cell_type: 'code',
      metadata: {},
      source: [step.sql, '', 'con.execute(step_sql)'],
      outputs: [],
      execution_count: null,
    });
  });

  cells.push({
    cell_type: 'code',
    metadata: {},
    source: ['result = con.execute("SELECT * FROM current_data").fetchall()', 'print(result)'],
    outputs: [],
    execution_count: null,
  });

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.10.0',
      },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
