import * as path from 'path';

import { TransformOperation, EngineType } from '../types/index.js';

import { buildPipelineSQL } from './pipeline.js';

function pythonString(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;
}

function pythonValue(value: unknown): string {
  const text = String(value ?? '').trim();
  if (/^-?(?:\d+\.?\d*|\.\d+)$/.test(text)) return text;
  if (/^true$/i.test(text)) return 'True';
  if (/^false$/i.test(text)) return 'False';
  if (/^null$/i.test(text)) return 'None';
  return pythonString(text);
}

function stringList(value: unknown, fallback?: unknown): string[] {
  const source = value ?? fallback;
  if (Array.isArray(source)) return source.filter((item): item is string => typeof item === 'string' && item.length > 0);
  return typeof source === 'string' && source.length > 0 ? [source] : [];
}

function polarsFilter(params: Record<string, unknown>): string {
  if (typeof params.condition === 'string' && params.condition.trim()) {
    return `pl.sql_expr(${pythonString(params.condition)})`;
  }
  const column = pythonString(String(params.column));
  const operator = String(params.operator);
  const value = pythonValue(params.value);
  const stringColumn = `pl.col(${column}).cast(pl.String)`;
  switch (operator) {
    case 'equals': return `pl.col(${column}) == ${value}`;
    case 'not_equals': return `pl.col(${column}) != ${value}`;
    case 'greater_than': return `pl.col(${column}) > ${value}`;
    case 'greater_equals': return `pl.col(${column}) >= ${value}`;
    case 'less_than': return `pl.col(${column}) < ${value}`;
    case 'less_equals': return `pl.col(${column}) <= ${value}`;
    case 'contains': return `${stringColumn}.str.contains(${pythonString(String(params.value ?? ''))}, literal=True)`;
    case 'not_contains': return `~${stringColumn}.str.contains(${pythonString(String(params.value ?? ''))}, literal=True)`;
    case 'starts_with': return `${stringColumn}.str.starts_with(${pythonString(String(params.value ?? ''))})`;
    case 'ends_with': return `${stringColumn}.str.ends_with(${pythonString(String(params.value ?? ''))})`;
    case 'is_null': return `pl.col(${column}).is_null()`;
    case 'is_not_null': return `pl.col(${column}).is_not_null()`;
    case 'between': return `pl.col(${column}).is_between(${value}, ${pythonValue(params.value2)})`;
    case 'in':
    case 'not_in': {
      const values = String(params.value ?? '').split(',').map(item => pythonValue(item.trim())).filter(Boolean);
      const expression = `pl.col(${column}).is_in([${values.join(', ')}])`;
      return operator === 'not_in' ? `~${expression}` : expression;
    }
    default: return `pl.lit(True)  # Unsupported filter operator: ${operator}`;
  }
}

function polarsReader(filePath: string): string {
  switch (path.extname(filePath).toLowerCase()) {
    case '.csv': return `pl.read_csv(${pythonString(filePath)})`;
    case '.tsv': return `pl.read_csv(${pythonString(filePath)}, separator="\\t")`;
    case '.jsonl': return `pl.read_ndjson(${pythonString(filePath)})`;
    case '.json': return `pl.read_json(${pythonString(filePath)})`;
    default: return `pl.read_parquet(${pythonString(filePath)})`;
  }
}

function duckdbReader(filePath: string): string {
  switch (path.extname(filePath).toLowerCase()) {
    case '.csv':
    case '.tsv': return 'read_csv_auto(?)';
    case '.json':
    case '.jsonl': return 'read_json_auto(?)';
    default: return 'read_parquet(?)';
  }
}

// ──────────────────────────────────────────────
// DuckDB Code Generation
// ──────────────────────────────────────────────

export function generateDuckDBSQL(steps: TransformOperation[], filePath?: string): string {
  const lines: string[] = [
    '-- Generated by QuackWrangler',
    '-- Engine: DuckDB',
    '',
  ];

  if (steps.length === 0) lines.push('-- No transforms applied', '');

  if (filePath) {
    lines.push(`-- Source: ${filePath}`);
    lines.push('');
  }

  lines.push(buildPipelineSQL(steps));
  lines.push(';');

  return lines.join('\n');
}

export function generateDuckDBPython(steps: TransformOperation[], filePath?: string): string {
  const lines: string[] = [
    '# Generated by QuackWrangler',
    '# Engine: DuckDB',
    '',
    'import duckdb',
    '',
    'con = duckdb.connect()',
    '',
  ];

  if (filePath) {
    lines.push(`# Source: ${filePath}`);
    if (path.extname(filePath).toLowerCase() === '.parquet') {
      lines.push(`df = con.read_parquet(${pythonString(filePath)})`);
      lines.push('con.register("current_data", df)');
    } else {
      lines.push(`source_path = ${pythonString(filePath)}`);
      lines.push(`con.execute("CREATE TABLE current_data AS SELECT * FROM ${duckdbReader(filePath)}", [source_path])`);
    }
    lines.push('');
  }

  const pipeline = buildPipelineSQL(steps).replace(/'''/g, "\\'\\'\\'");
  steps.forEach((step, index) => lines.push(`# Step ${index + 1}: ${step.description}`));
  lines.push(`pipeline_sql = r'''${pipeline}'''`);
  lines.push('result = con.execute(pipeline_sql).fetchall()');
  lines.push('print(result)');

  return lines.join('\n');
}

// ──────────────────────────────────────────────
// Polars Code Generation
// ──────────────────────────────────────────────

export function generatePolarsPython(steps: TransformOperation[], filePath?: string): string {
  const lines: string[] = [
    '# Generated by QuackWrangler',
    '# Engine: Polars',
    '',
    'import polars as pl',
    '',
  ];

  if (filePath) {
    lines.push(`# Source: ${filePath}`);
    lines.push(`df = ${polarsReader(filePath)}`);
  } else {
    lines.push('df = pl.DataFrame()');
  }

  lines.push('');

  steps.forEach((step, index) => {
    lines.push(`# Step ${index + 1}: ${step.description}`);
    const polarsCode = transformToPolars(step);
    lines.push(polarsCode);
    lines.push('');
  });

  lines.push('print(df)');
  lines.push('print(f"Shape: {df.shape}")');

  return lines.join('\n');
}

function transformToPolars(step: TransformOperation): string {
  switch (step.type) {
    case 'dropColumn':
    case 'drop_column': {
      const cols = stringList(step.params.columns, step.params.column);
      return `df = df.drop(${cols.map(c => `"${c}"`).join(', ')})`;
    }

    case 'renameColumn':
    case 'rename_column': {
      const renames = (step.params.renames as Record<string, string> | undefined) ?? { [step.params.oldName as string]: step.params.newName as string };
      const renameMap = Object.entries(renames)
        .map(([old, new_]) => `"${old}": "${new_}"`)
        .join(', ');
      return `df = df.rename({${renameMap}})`;
    }

    case 'filterRows':
    case 'filter_rows': {
      return `df = df.filter(${polarsFilter(step.params)})`;
    }

    case 'sortRows':
    case 'sort_rows': {
      const { column } = step.params as { column: string };
      const ascending = step.params.ascending ?? step.params.direction !== 'DESC';
      const nullsLast = ', nulls_last=True';
      return ascending
        ? `df = df.sort("${column}"${nullsLast})`
        : `df = df.sort("${column}", descending=True${nullsLast})`;
    }

    case 'castType':
    case 'cast_type': {
      const { column, targetType } = step.params as { column: string; targetType: string };
      const types: Record<string, string> = { VARCHAR: 'String', INTEGER: 'Int32', BIGINT: 'Int64', DOUBLE: 'Float64', BOOLEAN: 'Boolean', DATE: 'Date', TIMESTAMP: 'Datetime' };
      return `df = df.with_columns(pl.col("${column}").cast(pl.${types[targetType] ?? targetType}).alias("${column}"))`;
    }

    case 'fillMissing':
    case 'fill_nulls': {
      const { column, value } = step.params as { column: string; value: string };
      return `df = df.with_columns(pl.col("${column}").fill_null(${pythonValue(value)}))`;
    }

    case 'addColumn':
    case 'add_column': {
      const { name, expression } = step.params as { name: string; expression: string };
      return `df = df.with_columns(pl.sql_expr(${pythonString(expression)}).alias(${pythonString(name)}))`;
    }

    case 'deduplicate': {
      const cols = stringList(step.params.columns, step.params.column);
      return `df = df.unique(subset=[${cols.map(c => `"${c}"`).join(', ')}])`;
    }

    case 'aggregate': {
      const fn = String(step.params.function ?? '').toUpperCase();
      const column = String(step.params.column ?? '');
      const alias = String(step.params.alias || `${fn.toLowerCase()}_${column || 'rows'}`);
      const expression = fn === 'COUNT'
        ? 'pl.len()'
        : fn === 'COUNT_DISTINCT'
          ? `pl.col(${pythonString(column)}).n_unique()`
          : `pl.col(${pythonString(column)}).${fn.toLowerCase()}()`;
      const aggregation = `${expression}.alias(${pythonString(alias)})`;
      const groupBy = String(step.params.groupBy ?? '');
      return groupBy
        ? `df = df.group_by(${pythonString(groupBy)}).agg(${aggregation})`
        : `df = df.select(${aggregation})`;
    }

    case 'oneHotEncode': {
      const col = step.params.column as string;
      return [
        `categories = df["${col}"].unique().to_list()`,
        `for cat in categories:`,
        `    df = df.with_columns((pl.col("${col}") == cat).cast(pl.Int8).alias(f"${col}_{cat}"))`,
      ].join('\n    ');
    }

    case 'normalize': {
      const col = step.params.column as string;
      return `df = df.with_columns(((pl.col("${col}") - pl.col("${col}").min()) / (pl.col("${col}").max() - pl.col("${col}").min())).alias("${col}_normalized"))`;
    }

    case 'splitColumn': {
      const { column, delimiter } = step.params as { column: string; delimiter: string };
      return `df = df.with_columns(pl.col("${column}").str.split("${delimiter}").alias("${column}_parts"))`;
    }

    case 'mergeColumns': {
      const { separator, newColumn } = step.params as { separator: string; newColumn: string };
      const columns = stringList(step.params.columns, step.params.column);
      const castExpr = columns.map(c => `pl.col("${c}").cast(pl.Utf8)`).join(`.str.concat(pl.lit("${separator}")).`);
      return `df = df.with_columns(${castExpr}.alias("${newColumn}"))`;
    }

    default:
      return `# Unsupported transform for Polars: ${step.type}`;
  }
}

// ──────────────────────────────────────────────
// Unified Code Generation (engine-aware)
// ──────────────────────────────────────────────

export function generateCode(
  steps: TransformOperation[],
  engine: EngineType,
  filePath?: string,
  format: 'sql' | 'python' = 'python',
): string {
  if (engine === 'duckdb') {
    return format === 'sql'
      ? generateDuckDBSQL(steps, filePath)
      : generateDuckDBPython(steps, filePath);
  } else {
    return generatePolarsPython(steps, filePath);
  }
}

export function wrapAsView(step: TransformOperation, viewName: string): string {
  const safeName = viewName.replace(/[^a-zA-Z0-9_]/g, '_');
  return `CREATE OR REPLACE VIEW ${safeName} AS ${step.sql}`;
}

export function exportToNotebook(
  steps: TransformOperation[],
  engine: EngineType = 'duckdb',
  filePath?: string,
): string {
  const cells: Array<Record<string, unknown>> = [];

  cells.push({
    cell_type: 'markdown',
    metadata: {},
    source: [
      '# QuackWrangler Notebook',
      '',
      `Engine: ${engine === 'duckdb' ? 'DuckDB' : 'Polars'}`,
      '',
      'Data wrangling steps exported from QuackWrangler.',
    ],
  });

  if (engine === 'duckdb') {
    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['import duckdb', '', 'con = duckdb.connect()'],
      outputs: [],
      execution_count: null,
    });

    if (filePath) {
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [`df = con.read_parquet('${filePath}')`, 'con.register("current_data", df)'],
        outputs: [],
        execution_count: null,
      });
    }

    steps.forEach((step, index) => {
      cells.push({
        cell_type: 'markdown',
        metadata: {},
        source: [`## Step ${index + 1}: ${step.description}`],
      });

      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [step.sql, '', 'con.execute(step_sql)'],
        outputs: [],
        execution_count: null,
      });
    });

    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['result = con.execute("SELECT * FROM current_data").fetchall()', 'print(result)'],
      outputs: [],
      execution_count: null,
    });
  } else {
    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['import polars as pl'],
      outputs: [],
      execution_count: null,
    });

    if (filePath) {
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [`df = pl.read_parquet('${filePath}')`],
        outputs: [],
        execution_count: null,
      });
    }

    steps.forEach((step, index) => {
      cells.push({
        cell_type: 'markdown',
        metadata: {},
        source: [`## Step ${index + 1}: ${step.description}`],
      });

      const polarsCode = transformToPolars(step);
      cells.push({
        cell_type: 'code',
        metadata: {},
        source: [polarsCode],
        outputs: [],
        execution_count: null,
      });
    });

    cells.push({
      cell_type: 'code',
      metadata: {},
      source: ['print(df)', 'print(f"Shape: {df.shape}")'],
      outputs: [],
      execution_count: null,
    });
  }

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: 'Python 3',
        language: 'python',
        name: 'python3',
      },
      language_info: {
        name: 'python',
        version: '3.10.0',
      },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
