import { describe, it, expect } from 'vitest';
import { generateDuckDBSQL, generatePythonCode, wrapAsView } from '../../../src/transforms/codegen';
import { TransformOperation } from '../../../src/types';

describe('codegen', () => {
  const sampleSteps: TransformOperation[] = [
    {
      id: '1',
      type: 'dropColumn',
      params: { columns: ['old_col'] },
      sql: 'SELECT * EXCLUDE(old_col) FROM current_data',
      description: 'Drop column old_col',
    },
    {
      id: '2',
      type: 'fillMissing',
      params: { column: 'price', value: '0' },
      sql: 'SELECT *, COALESCE(price, 0) AS price_filled FROM current_data',
      description: 'Fill missing values in price',
    },
  ];

  describe('generateDuckDBSQL', () => {
    it('should generate valid SQL from steps', () => {
      const sql = generateDuckDBSQL(sampleSteps);
      expect(sql).toContain('Generated by QuackWrangler');
      expect(sql).toContain('EXCLUDE');
      expect(sql).toContain('COALESCE');
    });

    it('should include step descriptions', () => {
      const sql = generateDuckDBSQL(sampleSteps);
      expect(sql).toContain('Step 1');
      expect(sql).toContain('Step 2');
    });

    it('should handle empty steps', () => {
      const sql = generateDuckDBSQL([]);
      expect(sql).toContain('No transforms applied');
    });
  });

  describe('generatePythonCode', () => {
    it('should generate Python code with duckdb', () => {
      const python = generatePythonCode(sampleSteps);
      expect(python).toContain('import duckdb');
      expect(python).toContain('duckdb.connect');
    });

    it('should include step comments', () => {
      const python = generatePythonCode(sampleSteps);
      expect(python).toContain('Step 1');
      expect(python).toContain('Step 2');
    });

    it('should include execute calls', () => {
      const python = generatePythonCode(sampleSteps);
      expect(python).toContain('con.execute');
    });
  });

  describe('wrapAsView', () => {
    it('should create a view from a step', () => {
      const viewSql = wrapAsView(sampleSteps[0], 'my_view');
      expect(viewSql).toContain('CREATE OR REPLACE VIEW');
      expect(viewSql).toContain('my_view');
      expect(viewSql).toContain('EXCLUDE');
    });

    it('should sanitize view names', () => {
      const viewSql = wrapAsView(sampleSteps[0], 'my-view!@#');
      expect(viewSql).toContain('my_view___');
    });
  });
});
