import { describe, it, expect } from 'vitest';
import {
  generateDuckDBSQL,
  generateDuckDBPython,
  generatePolarsPython,
  generateCode,
  wrapAsView,
  exportToNotebook,
} from '../../../src/transforms/codegen';
import { TransformOperation } from '../../../src/types';

describe('codegen', () => {
  const sampleSteps: TransformOperation[] = [
    {
      id: '1',
      type: 'dropColumn',
      params: { columns: ['old_col'] },
      sql: 'SELECT * EXCLUDE(old_col) FROM current_data',
      description: 'Drop column old_col',
    },
    {
      id: '2',
      type: 'fillMissing',
      params: { column: 'price', value: '0' },
      sql: 'SELECT *, COALESCE(price, 0) AS price_filled FROM current_data',
      description: 'Fill missing values in price',
    },
  ];

  // ── DuckDB SQL ──────────────────────────────────────

  describe('generateDuckDBSQL', () => {
    it('should generate valid SQL from steps', () => {
      const sql = generateDuckDBSQL(sampleSteps);
      expect(sql).toContain('Generated by QuackWrangler');
      expect(sql).toContain('Engine: DuckDB');
      expect(sql).toContain('EXCLUDE');
      expect(sql).toContain('COALESCE');
    });

    it('should include file path when provided', () => {
      const sql = generateDuckDBSQL(sampleSteps, '/data/test.parquet');
      expect(sql).toContain('Source: /data/test.parquet');
    });

    it('should handle empty steps', () => {
      const sql = generateDuckDBSQL([]);
      expect(sql).toContain('No transforms applied');
    });
  });

  // ── DuckDB Python ───────────────────────────────────

  describe('generateDuckDBPython', () => {
    it('should generate Python code with duckdb', () => {
      const python = generateDuckDBPython(sampleSteps);
      expect(python).toContain('import duckdb');
      expect(python).toContain('duckdb.connect');
      expect(python).toContain('con.execute');
    });

    it('should include file path as read_parquet', () => {
      const python = generateDuckDBPython(sampleSteps, '/data/test.parquet');
      expect(python).toContain("read_parquet('/data/test.parquet')");
      expect(python).toContain('con.register("current_data"');
    });

    it('should include step comments', () => {
      const python = generateDuckDBPython(sampleSteps);
      expect(python).toContain('Step 1');
      expect(python).toContain('Step 2');
    });
  });

  // ── Polars Python ───────────────────────────────────

  describe('generatePolarsPython', () => {
    it('should generate Polars code', () => {
      const python = generatePolarsPython(sampleSteps);
      expect(python).toContain('import polars as pl');
      expect(python).toContain('Engine: Polars');
    });

    it('should include file path as read_parquet', () => {
      const python = generatePolarsPython(sampleSteps, '/data/test.parquet');
      expect(python).toContain("pl.read_parquet('/data/test.parquet')");
    });

    it('should generate drop column transform', () => {
      const python = generatePolarsPython(sampleSteps);
      expect(python).toContain('df.drop');
      expect(python).toContain('old_col');
    });

    it('should generate fill_null transform', () => {
      const python = generatePolarsPython(sampleSteps);
      expect(python).toContain('fill_null');
    });

    it('should handle empty steps', () => {
      const python = generatePolarsPython([]);
      expect(python).toContain('import polars as pl');
    });
  });

  // ── Unified generateCode ────────────────────────────

  describe('generateCode', () => {
    it('should generate DuckDB SQL when engine is duckdb', () => {
      const code = generateCode(sampleSteps, 'duckdb', undefined, 'sql');
      expect(code).toContain('Engine: DuckDB');
      expect(code).toContain('EXCLUDE');
    });

    it('should generate DuckDB Python when engine is duckdb', () => {
      const code = generateCode(sampleSteps, 'duckdb', undefined, 'python');
      expect(code).toContain('import duckdb');
    });

    it('should generate Polars Python when engine is polars', () => {
      const code = generateCode(sampleSteps, 'polars');
      expect(code).toContain('import polars as pl');
      expect(code).toContain('df.drop');
    });

    it('should default to python format', () => {
      const code = generateCode(sampleSteps, 'duckdb');
      expect(code).toContain('import duckdb');
    });
  });

  // ── wrapAsView ──────────────────────────────────────

  describe('wrapAsView', () => {
    it('should create a view from a step', () => {
      const viewSql = wrapAsView(sampleSteps[0], 'my_view');
      expect(viewSql).toContain('CREATE OR REPLACE VIEW');
      expect(viewSql).toContain('my_view');
      expect(viewSql).toContain('EXCLUDE');
    });

    it('should sanitize view names', () => {
      const viewSql = wrapAsView(sampleSteps[0], 'my-view!@#');
      expect(viewSql).toContain('my_view___');
    });
  });

  // ── exportToNotebook ────────────────────────────────

  describe('exportToNotebook', () => {
    it('should export DuckDB notebook', () => {
      const notebook = exportToNotebook(sampleSteps, 'duckdb');
      expect(notebook).toContain('duckdb');
      expect(notebook).toContain('nbformat');
    });

    it('should export Polars notebook', () => {
      const notebook = exportToNotebook(sampleSteps, 'polars');
      expect(notebook).toContain('polars');
      expect(notebook).toContain('nbformat');
    });

    it('should include file path in DuckDB notebook', () => {
      const notebook = exportToNotebook(sampleSteps, 'duckdb', '/data/test.parquet');
      expect(notebook).toContain("read_parquet('/data/test.parquet')");
    });

    it('should include file path in Polars notebook', () => {
      const notebook = exportToNotebook(sampleSteps, 'polars', '/data/test.parquet');
      expect(notebook).toContain("pl.read_parquet('/data/test.parquet')");
    });
  });
});
